# States that cannot be cancelled by the user (terminal or protected states)
_CANCELLABLE_STATES = {"PENDING", "ONHOLD", "PENDINGPAYMENT", "CONFIRMED", "PROCESSING", "SHIPPED"}

TRANSITIONS = {
    "PENDING": {
        "PENDINGBIOMETRICALVERIFICATION": "ONHOLD",
        "NOVERIFICATIONNEEDED": "PENDINGPAYMENT",
        "PAYMENTFAILED": "CANCELLED",
        "ORDERCANCELLED": "CANCELLED",
        "ORDERCANCELLEDBYUSER": "CANCELLED",
    },
    "ONHOLD": {
        "BIOMETRICALVERIFICATIONSUCCESSFUL": "PENDINGPAYMENT",
        "VERIFICATIONFAILED": "CANCELLED",
        "ORDERCANCELLEDBYUSER": "CANCELLED",
    },
    "PENDINGPAYMENT": {
        "PAYMENTSUCCESSFUL": "CONFIRMED",
        "ORDERCANCELLEDBYUSER": "CANCELLED",
    },
    "CONFIRMED": {
        "PREPARINGSHIPMENT": "PROCESSING",
        "ORDERCANCELLEDBYUSER": "CANCELLED",
    },
    "PROCESSING": {
        "ITEMDISPATCHED": "SHIPPED",
        "ORDERCANCELLEDBYUSER": "CANCELLED",
    },
    "SHIPPED": {
        "ITEMRECEIVEDBYCUSTOMER": "DELIVERED",
        "DELIVERYISSUE": "ONHOLD",
        "ORDERCANCELLEDBYUSER": "CANCELLED",
    },
    "DELIVERED": {},
    "CANCELLED": {},
}